export default function Home() {
  return (
    <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh", fontFamily: "sans-serif", background: "#0b0e1a", color: "#fff" }}>
      <div style={{ textAlign: "center" }}>
        <h1 style={{ fontSize: 24, fontWeight: 700, marginBottom: 8 }}>NxtZen IP Verify</h1>
        <p style={{ opacity: 0.5, fontSize: 14 }}>Verification links are generated by the bot.</p>
      </div>
    </div>
  );
}
